controller:
  serviceType: ClusterIP
  admin:
    createSecret: true
    user: admin
  ingress:
    enabled: false
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
  persistence:
    enabled: true
    size: 20Gi

agent:
  enabled: true
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

rbac:
  create: true
