# =========================
# Jenkins Controller Config
# =========================
controller:
  # Internal service (ALB will expose it)
  serviceType: ClusterIP

  # -------------------------
  # Ingress (AWS ALB)
  # -------------------------
  # ingress:
  #   enabled: true
  #   ingressClassName: alb

  #   hostName: jenkins.my-domain.com

  #   annotations:
  #     kubernetes.io/ingress.class: alb

  #     # ALB settings
  #     alb.ingress.kubernetes.io/scheme: internet-facing
  #     alb.ingress.kubernetes.io/target-type: ip
  #     alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'

  #     # Optional: group with ArgoCD (same ALB)
  #     alb.ingress.kubernetes.io/group.name: shared-alb

  # -------------------------
  # Node placement (jenkins node group)
  # -------------------------
  nodeSelector:
    workload/node-group: jenkins

  # -------------------------
  # Plugins
  # -------------------------
  installPlugins:
    - kubernetes:4423.vb_59f230b_ce53
    - workflow-aggregator:608.v67378e9d3db_1
    - git:5.10.1
    - configuration-as-code:2061.vc08919f7fc37
    # - aws-secrets-manager-credentials-provider:2.87.v49cc86c50c3b_ - Commented for POC, if uncomment then need to manage dependencies for this plugin

  # -------------------------
  # JCasC (basic)
  # -------------------------
  JCasC:
    defaultConfig: true
    configScripts:
      welcome-message: |
        jenkins:
          systemMessage: "Jenkins managed via Helm + JCasC"

  # -------------------------
  # Sidecar (auto reload JCasC)
  # -------------------------
  sidecars:
    configAutoReload:
      enabled: true

# -------------------------
# Persistence (EBS) DISABLED for POC, enable in Production
# -------------------------
persistence:
  enabled: false
  storageClass: ebs-csi
  accessMode: ReadWriteOnce
  size: 20Gi

# =========================
# Jenkins Agents Config
# =========================
agent:
  enabled: true

  # Agents in separate namespace
  namespace: jenkins-agents

  # Schedule only on agent node group
  nodeSelector:
    workload/node-group: jenkins-agents

# =========================
# RBAC
# =========================
rbac:
  create: true

# =========================
# Service Account (for IRSA)
# =========================
serviceAccount:
  create: true
  name: jenkins
